name: homecook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  simple_animations: ^2.3.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.25
  number_inc_dec: ^0.6.6
  logger: ^0.9.4
  flutter_secure_storage: ^3.3.5
  http: ^0.12.2
  image_picker:
  provider: ^4.3.2+2
  geolocator: ^5.3.0
  location: ^3.0.2
  mobile_number: ^1.0.3
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0
  international_phone_input: ^1.0.4
  fluttertoast: ^7.1.6
  scoped_model: ^1.0.1
  firebase_messaging: 
  flutter_rating_bar: ^3.2.0+1
  flutter_svg: ^0.18.0
  date_time_picker: "^1.1.1"
  webview_flutter: ^1.0.7
  flutter_time_date_picker: ^0.0.2
  flutter_time_picker_spinner: ^1.0.6+1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. 02
  # example:
  fonts:
    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada-Bold.ttf
        - asset: assets/fonts/Lemonada-Regular.ttf
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
